# Generated by Django 2.1.7 on 2019-05-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseSelection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='static/img/adm_query')),
            ],
        ),
    ]
