# Generated by Django 2.1 on 2019-04-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoreManagement', '0001_initial'),
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('classroom', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.MajorCourses')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Student')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeachersCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoreManagement.MajorCourses')),
                ('tno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Teacher')),
            ],
        ),
    ]
